# Site settings
title: Artificial Intelligence and Statistics Conference
email: aistats2020pc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "/aistats2020" # the subpath of your site, e.g. /blog/
#twitter_username: aistat
github_username:  aistats

author:
  name: AISTATS
comments: false
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: aistats

ghub:
  edit: true
  repository: aistats2020

# Build settings
markdown: kramdown

# change encoding for the generated output files to utf-8
encoding: utf-8

# Handling Reading
exclude: [ "accommodation.html", "andreas_krause.html", "david_blei.html", "jeniffer_hill.html", "student_volunteers_application.html" ]

image:
  file: Palermo.jpg
  width: 400

banner: TaorminaTheatre.jpg

credit_card_image: credit.png
